#!/usr/bin/env ruby -w

require_relative 'lib/dice'
require_relative 'lib/display'
require_relative 'lib/sounds'
require_relative 'lib/say'

include Say

def play_sound(sound)
  system("afplay #{sound}")
end

def special_rolls(rolls)
  result = nil
  if rolls.uniq.size == 1
    result = rolls.first
  end

  if result
    case result
    when 1 then say_snake_eyes
    when 6 then say_double_sixes
    else say_check_my_dubs
    end
  end
end

def maybe_drink!
  x = rand(50)
  if x == 0
    play_sound(Sounds::TAKE_SHOT)
    puts(Display::TAKE_SHOT)
    say_take_a_shot
    puts
  elsif x == 49
    play_sound(Sounds::POUND_BEER)
    puts(Display::POUND_BEER)
    say_pound_your_beer
    puts
  end
end

system('clear')
dice = Dice.new(1)
puts("Welcome to DICE ROLL!\n\n")
puts('Press enter to roll the dice!')
gets

loop do
  system('clear')
  play_sound(Sounds::DICE_ROLL)

  rolls = [dice.roll, dice.roll]

  maybe_drink!

  puts(Display::HASH[rolls.first])
  puts
  puts(Display::HASH[rolls.last])
  puts
  puts("Total score: #{ rolls.inject(&:+) }")

  special_rolls(rolls)

  puts('Press enter to roll the dice!')
  gets
end

